# Generated by Django 5.1.2 on 2024-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_oferta_product_oferta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oferta',
            new_name='Offer',
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['motive']},
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='shop_oferta_motivo_a6f656_idx',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='descuento',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='motivo',
            new_name='motive',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='oferta',
            new_name='offer',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='shop_offer_id_f68be1_idx',
            old_name='shop_oferta_id_294eeb_idx',
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['motive'], name='shop_offer_motive_e4daef_idx'),
        ),
    ]
